### ISSUE TITLE
Do all protocols 

### ISSUE THREAD

**Issue by NoRRt** [fscarmen/sing-box#6]
Do all protocols display the config output as links and QR codes separately for IP version 6 and 4?

**Comment by NoRRt** [comment]
For example:
 
ipv4 : hy2://example@example?insecure=1&sni=example.co                                                                                     m#HY2
    ---------------------------------------------------------------
    ipv6 : hy2://example@[example:example:example:example::1]:example?insecure=1&sni=example.com#HY2
****

**Comment by fscarmen** [comment]
The script distinguishes between v4 and v6 and outputs the url for the corresponding protocol, e.g.
IPv4 : hy2://85b4d89d-3ce7-40c0-bd3c-15ac764bc304@191.96.242.114:33333?obfs=salamander&obfs-password=85b4d89d-3ce7-40c0-bd3c-15ac764bc304&insecure=1#HYTRON815365597%20hysteria2
---------------------------------------------------------------
IPv6:  hy2://68fe8d27-cbc8-4e72-90b7-70d3bb69dfd3@[2605:8340:0:e:0:1234:1879:1]:8883?obfs=salamander&obfs-password=68fe8d27-cbc8-4e72-90b7-70d3bb69dfd3&insecure=1#hax%20hysteria2

QR is not provided for the time being, because it is not always possible to scan the code when it is displayed in the ssh utility.
