### ISSUE TITLE
[Feature Request] Request to add enable ECH option

### ISSUE THREAD

**Issue by ItTonySuperMan** [fscarmen/sing-box#8]
Request to add an option: whether to enable quantum ECH configuration

If you choose to enable ECH, quantum ECH will be automatically added to the corresponding configuration.

[Sing_box Official description](https://sing-box.sagernet.org/configuration/shared/tls/#ech-fields)

**Comment by fscarmen** [comment]
Thank you for your use and comments.
But sorry, not planning to add it for now.
This project is positioned as an aggregation script for each protocol, and each protocol has a number of fields and variables, so in order to avoid reducing interactions, only the classic scheme for each protocol will be used. Imagine 9 protocols with 2 interactions per protocol, there will be 18 interactions and the user will immediately [ctrl + c] .

**Comment by ItTonySuperMan** [comment]
> Thank you for your use and comments. But sorry, not planning to add it for now. This project is positioned as an aggregation script for each protocol, and each protocol has a number of fields and variables, so in order to avoid reducing interactions, only the classic scheme for each protocol will be used. Imagine 9 protocols with 2 interactions per protocol, there will be 18 interactions and the user will immediately [ctrl + c] .

**I understand that there are currently no ideas to add, thank the author for the reply.Hope to add more in the future**

Consider adding ECH as a global option to reduce user interaction. After all, tls is a required field for singbox. You can consider it as ECH to append the tls field.
